Blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog, name='Blog'),
    path('category/<category_id>/', views.category, name='category'),
]

Contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contact, name='Contact'),
]

Services/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.services, name='Services'),
]

Shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.shop, name='Shop'),
]

ShopCart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:id_product>/', views.add_product, name='add'),
    path('delete/<int:id_product>/', views.delete_product, name='delete'),
    path('subtract/<int:id_product>/', views.subtract_product, name='subtract'),
    path('clean/', views.clean_cart, name='clean'),
]

WebApp/urls.py
from django.urls import path
from WebApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='Home'),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WebProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('services/', include('Services.urls')),
    path('blog/', include('Blog.urls')),
    path('contact/', include('Contact.urls')),
    path('shop/', include('Shop.urls')),
    path('cart/', include('ShopCart.urls')),
    path('', include('WebApp.urls'))
]

#superUser, Fede 1234

Blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=50)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Post(models.Model):
    title=models.CharField(max_length=50)
    content=models.CharField(max_length=50, verbose_name="content")
    image=models.ImageField(upload_to='Blog', null=True, blank=True)
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    category=models.ManyToManyField(Category)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'

    def __str__(self):
        return self.title

Services/models.py
from django.db import models

# Create your models here.

class Service(models.Model):
    title=models.CharField(max_length=50)
    content=models.CharField(max_length=50, verbose_name="description")
    image=models.ImageField(upload_to='Services')
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Service'
        verbose_name_plural = 'Services'

    def __str__(self):
        return self.title

Shop/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.

class ProductCategory(models.Model):
    name=models.CharField(max_length=50, verbose_name='Name')
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="Product Category"
        verbose_name_plural="Product Categories"

    def __str__(self):
        return self.name

class Product(models.Model):
    name=models.CharField(max_length=50, verbose_name='Name')
    category=models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    image=models.ImageField(upload_to="shop", null=True, blank=True)
    availability=models.BooleanField(default=True)
    price=models.FloatField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name="Product"
        verbose_name_plural="Products"

ShopCart/models.py
from django.db import models

# Create your models here.

Contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label="Name", required=True, max_length=30)
    email = forms.EmailField(label="E-mail", required=True)
    message = forms.CharField(label="Message", widget=forms.Textarea)

Blog/views.py
from django.shortcuts import render
from Blog.models import Post, Category

# Create your views here.

def blog(request):
    posts = Post.objects.all()
    categories=Category.objects.all()

    return render(request, 'Blog/blog.html', {'posts': posts, 'categories': categories})

def category(request, category_id):
    category = Category.objects.get(id=category_id)
    posts = Post.objects.filter(category=category)

    return render(request, 'blog/category.html', {'category': category,'posts': posts})

Contact/views.py
from django.shortcuts import redirect, render
from .forms import ContactForm
from django.core.mail import send_mail

# Create your views here.

def contact(request):
    contact_form = ContactForm()

    if request.method == 'POST':
        contact_form = ContactForm(data=request.POST)

        if contact_form.is_valid():
            form_info = contact_form.cleaned_data

            try:
                send_mail('Contact Form from DjangoWebApp', form_info['message'], form_info.get('email', ''), ['yourEmail@gmail.com'])
                return redirect('/contact/?ok')

            except:
                return redirect('/contacto/?wrong')




    return render(request, 'Contact/contact.html', {'myForm': contact_form})

Services/views.py
from django.shortcuts import render
from Services.models import Service

# Create your views here.

def services(request):
    services = Service.objects.all()
    return render(request, 'Services/services.html', {'services': services})

Shop/views.py
from django.shortcuts import render
from .models import Product

# Create your views here.

def shop(request):
    products=Product.objects.all()
    return render(request, 'Shop/shop.html', {'products': products} )

ShopCart/views.py
from django.shortcuts import render, redirect
from .shopCart import Cart
from Shop.models import Product

# Create your views here.

def add_product(request, id_product):
    cart = Cart(request)
    product = Product.objects.get(id = id_product)
    cart.add(product = product)
    return redirect('Shop')

def delete_product(request, id_product):
    cart = Cart(request)
    product = Product.objects.get(id = id_product)
    cart.delete(product = product)
    return redirect('Shop')

def subtract_product(request, id_product):
    cart = Cart(request)
    product = Product.objects.get(id = id_product)
    cart.subtract(product = product)
    return redirect('Shop')

def clean_cart(request):
    cart = Cart(request)
    cart.clean()
    return redirect('Shop')

WebApp/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'WebApp/home.html')

Blog/templates/blog/blog.html
{% extends 'WebApp/base.html' %}

  {% load static %}

    {% block content %}

        {% for post in posts %}
     
     <div>
       <h2>{{post.title}}</h2>
       <p>{{post.content}}</p>
       <p>{{post.author}}</p>

       <p><img width="120px" height="120px" src="{{post.image.url}}" alt=""></p>
     </div>

     {% endfor %}

    <section>
      <div style="width: 75%;text-align: center; margin: auto;">
        Categorías:
        {% for category in categories %}

          <a href="{% url 'category' category.id %}">{{category.name}}</a> &nbsp;

        {% endfor %}
      </div>
    </section>

    {% endblock %}

Blog/templates/blog/category.html
{% extends 'WebApp/base.html' %}

  {% load static %}

    {% block content %}

        {% for post in posts %}
     
     <div>
       <h2>{{post.title}}</h2>
       <p>{{post.content}}</p>
       <p>{{post.author}}</p>

       <p><img width="120px" height="120px" src="{{post.image.url}}" alt=""></p>
     </div>

     {% endfor %}

    <section>
      <div style="width: 75%;text-align: center; margin: auto;">
        Categoría: {{category.name}}
      </div>
    </section>

    {% endblock %}

Contact/templates/contact/contact.html
{% extends 'WebApp/base.html' %}

  {% load static %}

    {% block content %}

      <div>
        {% if 'ok' in request.GET %}
          <p>Thanks for writing!</p>
        {% endif %}
        <form action="" method="POST"> {% csrf_token %}
          <table>
            {{myForm.as_table}}
          </table>
          <input type="submit" value="Send" name="" id="">
        </form>
      </div>

    {% endblock %}

Services/templates/services/services.html
{% extends 'WebApp/base.html' %}

  {% load static %}

    {% block content %}

     {% for service in services %}
     
     <div>
       <h2>{{service.title}}</h2>
       <p>{{service.content}}</p>

       <p><img width="120px" height="120px" src="{{service.image.url}}" alt=""></p>
     </div>

     {% endfor %}

    {% endblock %}

Shop/templates/cart/widget.html
<div>
    <div>
        <p>Shopping Cart</p>
    </div>
    <div>
        <p>Product</p>
        <p>Quantity</p>
        <p>Total Product</p>
    </div>
    {% if request.session.cart.items %}
        {% for key, value in request.session.cart.items %}
        <div>
            <p>{{value.name}}</p>
            <p>{{value.quantity}}</p>
            <div>
                <a href="{% url 'cart:add' value.id_product %}">SUMAR</a>
                <a href="{% url 'cart:subtract' value.id_product %}">RESTAR</a>
            <p>{{value.price}}</p>

            </div>
        </div>
        {% endfor %}
        <div>
            <p>Total: $ {{ cart_total }}</p>
        </div>

    {% else %}
    <div>
        <p>Nothing to buy...</p>
    </div>
    {% endif %}
</div>

Shop/templates/shop/shop.html
{% extends 'WebApp/base.html' %}

  {% load static %}

    {% block content %}

    <div>
      <div style="float: right;">
        {% include 'cart/widget.html' %}
      </div>
    </div>

     {% for product in products %}
      <div>
        <img src="{{product.image.url}}" alt="" width="200px" height="200px">
        <div>
          <p>{{product.name}}</p>
          <p>{{product.price}}</p>
        </div>

        <div>
          <a href="{% url 'cart:add' product.id %}">Add to cart</a>
        </div>
      </div>
     {% endfor %}
    
     {% endblock %}

WebApp/templates/WebApp/base.html
<html>

<head>

    {% load static %}
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap" rel="stylesheet">
     
    <!-- Styles -->
    <link href="{% static 'WebApp/css/main.css' %}" rel="stylesheet">
</head>

<body>
  <header>
    <nav>
      <div class="logo">
        Fedev
      </div>

      <ul class="nav-list">
        <li class="{% if request.path == '/' %}link-active{% endif %}">
          <a class="" href="{% url 'Home' %}">Home</a>
        </li>
        <li class="{% if request.path == '/services/' %}link-active{% endif %}">
          <a class="" href="{% url 'Services' %}">Services</a>
        </li>
        <li class="{% if request.path == '/shop/' %}link-active{% endif %}">
          <a class="" href="{% url 'Shop' %}">Shop</a>
        </li>
        <li class="{% if request.path == '/contact/' %}link-active{% endif %}">
          <a class="" href="{% url 'Contact' %}">Contact</a>
        </li>
        <li class="{% if request.path|slice:':6' == '/blog/' %}link-active{% endif %}">
          <a class="" href="{% url 'Blog' %}">Blog</a>
        </li>

      </ul>
    </nav>
  </header>

  {% block content %}
  {% endblock %}


    <!-- Footer -->
    <footer class="footer">
      <ul>
        <li><a href="#">Privacy Policy</a></li>
        <li><a href="#">Cookies</a></li>
      </ul>
	</footer>

</body>


</html>

WebApp/templates/WebApp/home.html
{% extends 'WebApp/base.html' %}

  {% load static %}

    {% block content %}

    <p>Home</p>
   
   {% endblock %}

WebApp/templates/WebApp/shop.html
{% extends 'WebApp/base.html' %}

  {% load static %}

    {% block content %}

     <p>Shop</p>
    
     {% endblock %}